### PR TITLE
1663 add back the consumer contract tests

### PR DESCRIPTION
**Pull request by constantin-ciobotaru**

### CODE REVIEW

**Comment by ryandawsonuk** [comment]
My concern with putting ref to snapshot repo in the test is that either we modify the test code during the release process or we accept that the release tag contains the snapshot reference. If the release tag contains the snapshot reference then at some point in the future the test on the release tag will stop working because the snapshot it depends on will no longer be available. Given those options there's a good case for just waiting for the bug fix from the contracts guys.

**Comment by constantin-ciobotaru** [comment]
Yah, that's ok. Honestly, I wanted to push that piece of code, because it was only in my local repo. Let's just keep the branch, without merging it. I'll update this PR after spring cloud release.

**Comment by constantin-ciobotaru** [comment]
Updated after spring cloud updated to Finchley.M7 by using the producer stubs as maven dependency on consumer side. The same version of the consumer should be on the producer side.

**Comment by Salaboy** [comment]
@constantin-ciobotaru what is the status of this? we are now in M8, is this still working? should we merge this one? if so please ping me in gitter

**Comment by constantin-ciobotaru** [comment]
@Salaboy I did rebased the branch and the tests are passing, so, yes, this should be merged.

**Pull request merged**
